all:
  hosts:
    master1:
      ansible_host: 192.168.10.12
      ip: 192.168.10.12
      access_ip: 192.168.10.12
    worker1:
      ansible_host: 192.168.10.8
      ip: 192.168.10.8
      access_ip: 192.168.10.8
    worker2:
      ansible_host: 192.168.10.32
      ip: 192.168.10.32
      access_ip: 192.168.10.32
    worker3:
      ansible_host: 192.168.10.11
      ip: 192.168.10.11
      access_ip: 192.168.10.11
    worker4:
      ansible_host: 192.168.10.31
      ip: 192.168.10.31
      access_ip: 192.168.10.31
  children:
    kube_control_plane:
      hosts:
        master1:
    kube_node:
      hosts:
        worker1:
        worker2:
        worker3:
        worker4:
    etcd:
      hosts:
        master1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
